export default {
    getSessionKeyByCode: '/applet/get-session',
    decryptData: '/applet/decrypt-data',
    getTestData: '/test/test',
    getCityList: '/index/city-list',
    getHouseList: '/house/list',
    getSearchKeyList: '/api/search/key/list',
    getHouseSearchHot: '/house/hot-search',
    getHouseById: '/house/get',
    getHouseAttr: '/house/attr',
    getHouseNew: '/api/house/new',
    getHouseAlbum: '/api/house/all-image',
    getHouseSurround: '/api/house/surround',
    getHouseSand: '/house/get-sand',
    getHouseSandRoom: '/house/find-sand-room',
    getHouseAsk: '/house/ask-list',
    postHouseAsk: '/house/ask',
    getHouseComment: '/house/comment-list',
    postHouseComment: '/house/comment',
    getHouseTypeList: '/house/room-list',
    uploadFile: '/file/upload'
}